name:                github-classroom-helper
version:             0.1.0.0
github:              liontiger23/github-classroom-helper
license:             MIT
author:              Ivan Trepakov
maintainer:          liontiger23@gmail.com
copyright:           Copyright (c) 2024 Ivan Trepakov

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/liontiger23/github-classroom-helper#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - base64-bytestring
  - yaml
  - xml-conduit
  - http-types
  - unliftio-core
  - bytestring
  - github-rest
  - aeson
  - aeson-schemas
  - split
  - boxes
  - containers
  - doctemplates
  - doclayout
  - optparse-applicative
  - async

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  github-classroom-helper-exe:
    main:             Main.hs
    source-dirs:      app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-classroom-helper

tests:
  github-classroom-helper-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - github-classroom-helper
    - tasty
    - tasty-hunit
